// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpoeBE0qzcqfR-iTgBP20NBwfxX7XA0rg',
    appId: '1:740737504177:android:a329130d38da8af787a390',
    messagingSenderId: '740737504177',
    projectId: 'civichaven-9fb00',
    storageBucket: 'civichaven-9fb00.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmxNJ7sxftz5ei2TwakyEv6wVxP7EUIb8',
    appId: '1:740737504177:web:b3efd5adcc0dd72187a390',
    messagingSenderId: '740737504177',
    projectId: 'civichaven-9fb00',
    authDomain: 'civichaven-9fb00.firebaseapp.com',
    storageBucket: 'civichaven-9fb00.firebasestorage.app',
    measurementId: 'G-X5VGHG39V7',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAscUHACLOBsWVXVwtyXo05KTZbptLsy50',
    appId: '1:740737504177:ios:bc71edb6be83633487a390',
    messagingSenderId: '740737504177',
    projectId: 'civichaven-9fb00',
    storageBucket: 'civichaven-9fb00.firebasestorage.app',
    iosClientId: '740737504177-6nundkg1sivgsqgv2873g3gfbqr820q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.civicHaven',
  );
}
